USE [master]
GO

/****** Object:  Database [TestShop]    Script Date: 11/27/2023 8:56:30 PM ******/
CREATE DATABASE [TestShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\TestShop.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TestShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\TestShop_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TestShop] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestShop] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TestShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestShop] SET  MULTI_USER 
GO

ALTER DATABASE [TestShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestShop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TestShop] SET  READ_WRITE 
GO

